// Errors
export const ERROR = 'ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'

// Success
export const SET_SUCCESS = 'SET_SUCCESS'
export const CLEAR_SUCCESS = 'CLEAR_SUCCESS'

// Roles & Permissions
export const GET_PERMISSIONS = 'GET_PERMISSIONS';
export const GETTING_PERMISSIONS = 'GETTING_PERMISSIONS';
export const GET_ROLES = 'GET_ROLES';
export const GETTING_ROLES = 'GETTING_ROLES';
export const CREATE_ROLE = 'CREATE_ROLE';
export const CREATING_ROLE = 'CREATING_ROLE';
export const UPDATE_ROLE = 'UPDATE_ROLE';
export const UPDATING_ROLE = 'UPDATING_ROLE';
export const ROLES_PERMISSIONS_ERROR = 'ROLES_PERMISSIONS_ERROR';

// locations
export const GET_LOCATIONS = 'GET_LOCATIONS';
export const GETTING_LOCATIONS = 'GETTING_LOCATIONS';
export const CREATE_LOCATION = 'CREATE_LOCATION';
export const CREATING_LOCATION = 'CREATING_LOCATION';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const UPDATING_LOCATION = 'UPDATING_LOCATION';
export const DELETE_LOCATION = 'DELETE_LOCATION';
export const DELETING_LOCATION = 'DELETING_LOCATION';
export const LOCATIONS_ERROR = 'LOCATIONS_ERROR';

// assets
export const GET_ASSETS = 'GET_ASSETS';
export const GETTING_ASSETS = 'GETTING_ASSETS';
export const CREATE_ASSET = 'CREATE_ASSET';
export const CREATING_ASSET = 'CREATING_ASSET';
export const UPDATE_ASSET = 'UPDATE_ASSET';
export const UPDATING_ASSET = 'UPDATING_ASSET';
export const DELETE_ASSET = 'DELETE_ASSET';
export const DELETING_ASSET = 'DELETING_ASSET';
export const ASSETS_ERROR = 'ASSETS_ERROR';

// Audit logs
export const GET_AUDIT_LOGS = 'GET_AUDIT_LOGS';
export const GETTING_AUDIT_LOGS = 'GETTING_AUDIT_LOGS';
export const AUDIT_LOGS_ERROR = 'AUDIT_LOGS_ERROR';
