// Errors
export const ERROR = 'ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'

// Success
export const SET_SUCCESS = 'SET_SUCCESS'
export const CLEAR_SUCCESS = 'CLEAR_SUCCESS'

// Roles & Permissions
export const GET_PERMISSIONS = 'GET_PERMISSIONS';
export const GETTING_PERMISSIONS = 'GETTING_PERMISSIONS';
export const GET_ROLES = 'GET_ROLES';
export const GETTING_ROLES = 'GETTING_ROLES';
export const CREATE_ROLE = 'CREATE_ROLE';
export const CREATING_ROLE = 'CREATING_ROLE';
export const UPDATE_ROLE = 'UPDATE_ROLE';
export const UPDATING_ROLE = 'UPDATING_ROLE';
export const ROLES_PERMISSIONS_ERROR = 'ROLES_PERMISSIONS_ERROR';

// locations
export const GET_LOCATIONS = 'GET_LOCATIONS';
export const GETTING_LOCATIONS = 'GETTING_LOCATIONS';
export const CREATE_LOCATION = 'CREATE_LOCATION';
export const CREATING_LOCATION = 'CREATING_LOCATION';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const UPDATING_LOCATION = 'UPDATING_LOCATION';
export const DELETE_LOCATION = 'DELETE_LOCATION';
export const DELETING_LOCATION = 'DELETING_LOCATION';
export const LOCATIONS_ERROR = 'LOCATIONS_ERROR';

// assets
export const GET_ASSETS = 'GET_ASSETS';
export const GETTING_ASSETS = 'GETTING_ASSETS';
export const CREATE_ASSET = 'CREATE_ASSET';
export const CREATING_ASSET = 'CREATING_ASSET';
export const UPDATE_ASSET = 'UPDATE_ASSET';
export const UPDATING_ASSET = 'UPDATING_ASSET';
export const DELETE_ASSET = 'DELETE_ASSET';
export const DELETING_ASSET = 'DELETING_ASSET';
export const ASSETS_ERROR = 'ASSETS_ERROR';

// events
export const GET_EVENTS = 'GET_EVENTS';
export const GETTING_EVENTS = 'GETTING_EVENTS';
export const CREATE_EVENT = 'CREATE_EVENT';
export const CREATING_EVENT = 'CREATING_EVENT';
export const UPDATE_EVENT = 'UPDATE_EVENT';
export const UPDATING_EVENT = 'UPDATING_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';
export const DELETING_EVENT = 'DELETING_EVENT';
export const EVENTS_ERROR = 'EVENTS_ERROR';

// Products
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GETTING_PRODUCTS = 'GETTING_PRODUCTS';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const CREATING_PRODUCT = 'CREATING_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const UPDATING_PRODUCT = 'UPDATING_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETING_PRODUCT = 'DELETING_PRODUCT';
export const PRODUCTS_ERROR = 'PRODUCTS_ERROR';

// Batches
export const GET_BATCHES = 'GET_BATCHES';
export const GETTING_BATCHES = 'GETTING_BATCHES';
export const CREATE_BATCH = 'CREATE_BATCH';
export const CREATING_BATCH = 'CREATING_BATCH';
export const UPDATE_BATCH = 'UPDATE_BATCH';
export const UPDATING_BATCH = 'UPDATING_BATCH';
export const DELETE_BATCH = 'DELETE_BATCH';
export const DELETING_BATCH = 'DELETING_BATCH';
export const BATCHES_ERROR = 'BATCHES_ERROR';

// notifications
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const GETTING_NOTIFICATIONS = 'GETTING_NOTIFICATIONS';
export const NOTIFICATIONS_ERROR = 'NOTIFICATIONS_ERROR';

// Users
export const GET_USERS = 'GET_USERS';
export const GETTING_USERS = 'GETTING_USERS';
export const USERS_ERROR = 'USERS_ERROR';

// Audit logs
export const GET_AUDIT_LOGS = 'GET_AUDIT_LOGS';
export const GETTING_AUDIT_LOGS = 'GETTING_AUDIT_LOGS';
export const AUDIT_LOGS_ERROR = 'AUDIT_LOGS_ERROR';
