
export const placeholderEvents = [
  {
    id: 'event-001',
    producer: 'producer-001',
    asset: 'asset-001',
    eventCategory: 'production',
    eventTypeCategory: 'planting',
    eventType: 'seed-application',
    title: 'Seed Application Batch A',
    date: '2024-05-15T07:30:00.000Z',
    location: 'location-001',
    performedBy: 'user-101',
    performedByName: 'John Farmer',
    recordedOffline: false,
    notes: [
      {
        note: 'Hybrid maize seeds applied across the north section with row spacing verified after planting.',
        createdBy: 'user-101',
        createdByName: 'John Farmer',
      },
    ],
    attachments: ['seed-application-log.pdf', 'field-photo-15-may.jpg'],
    quantityAffected: 1200,
    weightAffected: null,
    costEstimate: 245000,
    mortalityCount: null,
    nextDueDate: '2024-06-01T08:00:00.000Z',
    createdBy: 'user-101',
    createdByName: 'John Farmer',
    createdAt: '2024-05-15T09:00:00.000Z',
    updatedAt: '2024-05-15T09:00:00.000Z',
  },
  {
    id: 'event-002',
    producer: 'producer-001',
    asset: 'asset-001',
    eventCategory: 'quality',
    eventTypeCategory: 'inspection',
    eventType: 'germination-check',
    title: 'Germination Inspection',
    date: '2024-06-01T10:15:00.000Z',
    location: 'location-001',
    performedBy: 'user-102',
    performedByName: 'Field Supervisor',
    recordedOffline: true,
    notes: [
      {
        note: 'Emergence rate measured at 91% with two rows flagged for light replanting.',
        createdBy: 'user-102',
        createdByName: 'Field Supervisor',
      },
    ],
    attachments: ['inspection-sheet.pdf'],
    quantityAffected: 1100,
    weightAffected: null,
    costEstimate: 18000,
    mortalityCount: null,
    nextDueDate: '2024-06-10T08:00:00.000Z',
    createdBy: 'user-102',
    createdByName: 'Field Supervisor',
    createdAt: '2024-06-01T12:30:00.000Z',
    updatedAt: '2024-06-02T07:45:00.000Z',
  },
  {
    id: 'event-003',
    producer: 'producer-001',
    asset: 'asset-002',
    eventCategory: 'health',
    eventTypeCategory: 'vaccination',
    eventType: 'booster-dose',
    title: 'Routine Vaccination Booster',
    date: '2024-06-10T06:45:00.000Z',
    location: 'location-002',
    performedBy: 'user-103',
    performedByName: 'Livestock Vet',
    recordedOffline: false,
    notes: [
      {
        note: 'Booster dose administered to the full herd with temperature readings logged post-treatment.',
        createdBy: 'user-103',
        createdByName: 'Livestock Vet',
      },
    ],
    attachments: ['vaccination-batch-card.pdf'],
    quantityAffected: 45,
    weightAffected: 1260,
    costEstimate: 98000,
    mortalityCount: 0,
    nextDueDate: '2024-09-10T08:00:00.000Z',
    createdBy: 'user-103',
    createdByName: 'Livestock Vet',
    createdAt: '2024-06-10T08:10:00.000Z',
    updatedAt: '2024-06-10T08:10:00.000Z',
  },
  {
    id: 'event-004',
    producer: 'producer-001',
    asset: 'asset-003',
    eventCategory: 'processing',
    eventTypeCategory: 'harvest',
    eventType: 'selective-harvest',
    title: 'Selective Tomato Harvest',
    date: '2024-06-08T05:50:00.000Z',
    location: 'location-001',
    performedBy: 'user-104',
    performedByName: 'Greenhouse Tech',
    recordedOffline: false,
    notes: [
      {
        note: 'First ripe clusters removed for premium market delivery; unripe sections left for follow-up harvest.',
        createdBy: 'user-104',
        createdByName: 'Greenhouse Tech',
      },
    ],
    attachments: ['harvest-weights.csv', 'packing-photo.jpg'],
    quantityAffected: 320,
    weightAffected: 840,
    costEstimate: 165000,
    mortalityCount: null,
    nextDueDate: '2024-06-12T08:00:00.000Z',
    createdBy: 'user-104',
    createdByName: 'Greenhouse Tech',
    createdAt: '2024-06-08T07:20:00.000Z',
    updatedAt: '2024-06-08T07:20:00.000Z',
  },
  {
    id: 'event-005',
    producer: 'producer-001',
    asset: 'asset-004',
    eventCategory: 'movement',
    eventTypeCategory: 'transfer',
    eventType: 'batch-relocation',
    title: 'Layer Batch Relocation',
    date: '2024-05-28T13:10:00.000Z',
    location: 'location-003',
    performedBy: 'user-105',
    performedByName: 'Poultry Manager',
    recordedOffline: true,
    notes: [
      {
        note: 'Bird batch moved to ventilated pen block after cleaning and line disinfection.',
        createdBy: 'user-105',
        createdByName: 'Poultry Manager',
      },
    ],
    attachments: [],
    quantityAffected: 1000,
    weightAffected: null,
    costEstimate: 42000,
    mortalityCount: 3,
    nextDueDate: null,
    createdBy: 'user-105',
    createdByName: 'Poultry Manager',
    createdAt: '2024-05-28T14:00:00.000Z',
    updatedAt: '2024-05-29T08:20:00.000Z',
  },
  {
    id: 'event-006',
    producer: 'producer-001',
    asset: 'asset-005',
    eventCategory: 'export',
    eventTypeCategory: 'inspection',
    eventType: 'pre-export-compliance-check',
    title: 'Pre-Export Compliance Check',
    date: '2024-06-02T11:30:00.000Z',
    location: 'location-002',
    performedBy: 'user-106',
    performedByName: 'Compliance Officer',
    recordedOffline: false,
    notes: [
      {
        note: 'Moisture, bagging integrity, and trace tags cleared for exporter intake.',
        createdBy: 'user-106',
        createdByName: 'Compliance Officer',
      },
    ],
    attachments: ['compliance-checklist.pdf', 'lot-tags.zip'],
    quantityAffected: 180,
    weightAffected: 5400,
    costEstimate: 35000,
    mortalityCount: null,
    nextDueDate: '2024-06-15T08:00:00.000Z',
    createdBy: 'user-106',
    createdByName: 'Compliance Officer',
    createdAt: '2024-06-02T12:10:00.000Z',
    updatedAt: '2024-06-03T09:25:00.000Z',
  },
]

export const getEventsForAsset = (assetId) => {
  return placeholderEvents
    .filter((event) => event.asset === assetId)
    .sort((firstEvent, secondEvent) => new Date(secondEvent.date) - new Date(firstEvent.date))
}

export const getEventsForLocation = (locationId) => {
  return placeholderEvents
    .filter((event) => event.location === locationId)
    .sort((firstEvent, secondEvent) => new Date(secondEvent.date) - new Date(firstEvent.date))
}

export const getEventById = (eventId) => {
  return placeholderEvents.find((event) => event.id === eventId)
}