export const placeholderLocations = [
  {
    id: 'loc-001',
    producer: 'producer-placeholder-01',
    latitude: 7.7337,
    longitude: 8.536,
    state: 'Benue',
    lga: 'Makurdi',
    addressDescription: 'North Bank farmlands, near River Benue floodplain',
    landSize: 12.4,
    waterSourceType: 'river',
    soilType: 'loamy',
    createdBy: 'user-placeholder-01',
    createdAt: '2026-05-03T10:30:00.000Z',
  },
  {
    id: 'loc-002',
    producer: 'producer-placeholder-01',
    latitude: 7.1902,
    longitude: 8.1298,
    state: 'Benue',
    lga: 'Gboko',
    addressDescription: 'Mkar agricultural belt, 3km off Gboko-Aliade road',
    landSize: 8.1,
    waterSourceType: 'borehole',
    soilType: 'sandy-loam',
    createdBy: 'user-placeholder-01',
    createdAt: '2026-05-08T08:12:00.000Z',
  },
  {
    id: 'loc-003',
    producer: 'producer-placeholder-02',
    latitude: 7.5293,
    longitude: 7.8721,
    state: 'Benue',
    lga: 'Guma',
    addressDescription: 'Daudu corridor, irrigated crop section near canal channel',
    landSize: 15.6,
    waterSourceType: 'irrigation-canal',
    soilType: 'silt-loam',
    createdBy: 'user-placeholder-02',
    createdAt: '2026-05-12T13:45:00.000Z',
  },
  {
    id: 'loc-004',
    producer: 'producer-placeholder-03',
    latitude: 7.8814,
    longitude: 8.8962,
    state: 'Benue',
    lga: 'Gwer East',
    addressDescription: 'Ikpayongo mixed farm cluster, east paddock section',
    landSize: 10.3,
    waterSourceType: 'well',
    soilType: 'clay-loam',
    createdBy: 'user-placeholder-03',
    createdAt: '2026-05-15T11:05:00.000Z',
  },
  {
    id: 'loc-005',
    producer: 'producer-placeholder-04',
    latitude: 7.8209,
    longitude: 9.2834,
    state: 'Benue',
    lga: 'Vandeikya',
    addressDescription: 'Mbaduku upland farms, cassava and yam production block',
    landSize: 6.8,
    waterSourceType: 'rain-fed',
    soilType: 'laterite',
    createdBy: 'user-placeholder-04',
    createdAt: '2026-05-19T07:18:00.000Z',
  },
  {
    id: 'loc-006',
    producer: 'producer-placeholder-05',
    latitude: 7.0513,
    longitude: 9.7042,
    state: 'Benue',
    lga: 'Oju',
    addressDescription: 'Aner road extension, lowland rice demonstration farm',
    landSize: 14.2,
    waterSourceType: 'stream',
    soilType: 'silty',
    createdBy: 'user-placeholder-05',
    createdAt: '2026-05-23T16:24:00.000Z',
  },
  {
    id: 'loc-007',
    producer: 'producer-placeholder-05',
    latitude: 6.8014,
    longitude: 8.5271,
    state: 'Benue',
    lga: 'Otukpo',
    addressDescription: 'Otukpo outskirts, poultry feed maize growth zone',
    landSize: 5.9,
    waterSourceType: 'harvested-rainwater',
    soilType: 'mixed',
    createdBy: 'user-placeholder-05',
    createdAt: '2026-05-27T10:02:00.000Z',
  },
  {
    id: 'loc-008',
    producer: 'producer-placeholder-06',
    latitude: 7.3021,
    longitude: 8.9463,
    state: 'Benue',
    lga: 'Konshisha',
    addressDescription: 'Tse-Agberagba axis, upland sesame and soybean farms',
    landSize: 9.7,
    waterSourceType: 'pond',
    soilType: 'sandy',
    createdBy: 'user-placeholder-06',
    createdAt: '2026-06-01T12:40:00.000Z',
  },
  {
    id: 'loc-009',
    producer: 'producer-placeholder-07',
    latitude: 7.4572,
    longitude: 8.5517,
    state: 'Benue',
    lga: 'Tarka',
    addressDescription: 'Wannune cluster plots, near seasonal stream crossing',
    landSize: 11.5,
    waterSourceType: 'stream',
    soilType: 'silt-loam',
    createdBy: 'user-placeholder-07',
    createdAt: '2026-06-06T09:22:00.000Z',
  },
  {
    id: 'loc-010',
    producer: 'producer-placeholder-08',
    latitude: 7.8465,
    longitude: 8.821,
    state: 'Benue',
    lga: 'Gwer West',
    addressDescription: 'Naka farm ring, mixed vegetable and legume production area',
    landSize: 7.4,
    waterSourceType: 'borehole',
    soilType: 'loamy',
    createdBy: 'user-placeholder-08',
    createdAt: '2026-06-11T14:58:00.000Z',
  },
]

export const locationAssets = {
  'loc-001': [
    { id: 'asset-001', name: 'Makurdi Rice Plot A', type: 'crop', quantity: '4.2 ha', status: 'active' },
    { id: 'asset-003', name: 'Cassava Cluster NB-2', type: 'crop', quantity: '2.8 ha', status: 'ready-for-harvest' },
    { id: 'asset-004', name: 'Irrigation Pump Unit 3', type: 'equipment', quantity: '1 unit', status: 'active' },
  ],
  'loc-002': [
    { id: 'asset-002', name: 'Soybean Block Mkar-1', type: 'crop', quantity: '3.1 ha', status: 'growing' },
    { id: 'asset-005', name: 'Groundnut Section G-4', type: 'crop', quantity: '1.9 ha', status: 'harvested' },
  ],
}

export const locationEvents = {
  'loc-001': [
    {
      id: 'evt-301',
      title: 'Soil Health Inspection',
      date: '2026-06-22',
      type: 'inspection',
      status: 'completed',
      note: 'Organic matter improved by 12% versus previous quarter.',
    },
    {
      id: 'evt-302',
      title: 'Flood Risk Drill',
      date: '2026-06-19',
      type: 'safety',
      status: 'completed',
      note: 'Emergency drainage channel opened before heavy rain period.',
    },
    {
      id: 'evt-303',
      title: 'Regulatory Spot Check',
      date: '2026-06-27',
      type: 'compliance',
      status: 'upcoming',
      note: 'Prepare pesticide use log and labour safety register.',
    },
  ],
  'loc-002': [
    {
      id: 'evt-401',
      title: 'Water Test Collection',
      date: '2026-06-18',
      type: 'quality',
      status: 'completed',
      note: 'Borehole source met all baseline quality checks.',
    },
    {
      id: 'evt-402',
      title: 'Yield Forecast Review',
      date: '2026-06-29',
      type: 'planning',
      status: 'upcoming',
      note: 'Update projected tonnage before exporter demand window.',
    },
  ],
}
